#!/usr/bin/with-contenv bash

echo "Running MySQL database initializations and migrations."

export PATH=/var/www/bin:$PATH

# roundcube
echo "Initializing MySQL for roundcube."
initdb.sh --dir /var/www/SQL

# plugins
while read dir; do
  echo "Initializing MySQL for ${dir}."
  initdb.sh --dir $dir
done < /var/www/.plugin_db_init
